# LLM / GigaChat
GIGACHAT_CREDENTIALS = "MjYzZDVhY2MtMmYyNi00ZDY5LThkMDItYzk4N2YxZTI0ZDdiOmVlYmI2OTExLWVkYjUtNDNlYy04MTU3LWE3YjY0YjRkZTllZg=="
GIGACHAT_SCOPE = "GIGACHAT_API_PERS"
GIGACHAT_MODEL = "GigaChat-Lite"

# Пути
ALLURE_RESULTS_DIR = "allure-results"

# Опционально: таймауты, лимиты запросов, прокси
HTTP_TIMEOUT = 30
VERIFY_SSL = False
